version: '3.7'

services:
  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1 max_nesting_level=512 remote_autostart=0 profiler_enable_trigger=off  remote_port=9010"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      test-network:
        ipv4_address: 192.168.220.4

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      test-network:
        ipv4_address: 192.168.220.5

  database:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: webmaster
      POSTGRES_USER: webmaster
      POSTGRES_DB: talent
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      test-network:
        ipv4_address: 192.168.220.7

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    links:
      - database
    networks:
      test-network:
        ipv4_address: 192.168.220.8

volumes:
  database:
    driver: 'local'

networks:
  test-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
