version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/app:cached
    container_name: php
    ports:
      - "9000:9000"

  database:
    image: library/postgres:12-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: webmaster
      POSTGRES_USER: webmaster
      POSTGRES_DB: talent
      PGDATA: /var/lib/postgresql/data/pgdata

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8082:8080
    links:
      - database

volumes:
  database:
    driver: 'local'
